<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2026-09-08]

namespace MagratheaExplorer\File\Base;

use Magrathea2\MagratheaModelControl;

class FileControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaExplorer\File";
	protected static $modelName = "File";
	protected static $dbTable = "files";
}
