<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2026-09-08]

namespace MagratheaExplorer\File\Base;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class TagBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name;
	protected $autoload = null;

	public function __construct( $id=0 ){
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "tags";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";
	}

	public function GetControl() {
		return new \MagratheaExplorer\File\Base\TagControlBase();
	}

}
