<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2026-09-08]

namespace MagratheaExplorer\Key\Base;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class KeyBase extends MagratheaModel implements iMagratheaModel {

	public $id, $uuid, $name, $uses, $usage_limit, $total_size, $usage_limit_mb, $expiration, $active;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct( $id=0 ){
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "access_keys";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["uuid"] = "uuid";
		$this->dbValues["name"] = "string";
		$this->dbValues["uses"] = "int";
		$this->dbValues["usage_limit"] = "int";
		$this->dbValues["total_size"] = "int";
		$this->dbValues["usage_limit_mb"] = "int";
		$this->dbValues["expiration"] = "datetime";
		$this->dbValues["active"] = "boolean";
		$this->dbValues["created_at"] = "datetime";
		$this->dbValues["updated_at"] = "datetime";

		$this->relations["properties"]["Folders"] = null;
		$this->relations["methods"]["Folders"] = "GetFolders";
		$this->relations["lazyload"]["Folders"] = "true";

		$this->relations["properties"]["Files"] = null;
		$this->relations["methods"]["Files"] = "GetFiles";
		$this->relations["lazyload"]["Files"] = "true";

		$this->relations["properties"]["ScheduledDeletions"] = null;
		$this->relations["methods"]["ScheduledDeletions"] = "GetScheduledDeletions";
		$this->relations["lazyload"]["ScheduledDeletions"] = "true";
	}

	public function GetControl() {
		return new \MagratheaExplorer\Key\Base\KeyControlBase();
	}

	// >>> relations:
	public function GetFolders(){
		if($this->relations["properties"]["Folders"] != null) return $this->relations["properties"]["Folders"];
		$pk = $this->dbPk;
		$this->relations["properties"]["Folders"] = \MagratheaExplorer\Folder\Base\FolderControlBase::GetWhere(["key_id" => $this->$pk]);
		return $this->relations["properties"]["Folders"];
	}
	public function GetFiles(){
		if($this->relations["properties"]["Files"] != null) return $this->relations["properties"]["Files"];
		$pk = $this->dbPk;
		$this->relations["properties"]["Files"] = \MagratheaExplorer\File\Base\FileControlBase::GetWhere(["key_id" => $this->$pk]);
		return $this->relations["properties"]["Files"];
	}
	public function GetScheduledDeletions(){
		if($this->relations["properties"]["ScheduledDeletions"] != null) return $this->relations["properties"]["ScheduledDeletions"];
		$pk = $this->dbPk;
		// GetSimpleWhere(), not GetWhere(): scheduled_deletions has no created_at column,
		// and array-form GetWhere() unconditionally appends "ORDER BY created_at DESC".
		$this->relations["properties"]["ScheduledDeletions"] = \MagratheaExplorer\Key\Base\ScheduledDeletionControlBase::GetSimpleWhere("`key_id` = ".(int)$this->$pk);
		return $this->relations["properties"]["ScheduledDeletions"];
	}

}
