<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2026-09-08]

namespace MagratheaExplorer\Folder\Base;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class FolderBase extends MagratheaModel implements iMagratheaModel {

	public $id, $key_id, $parent_id, $name;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct( $id=0 ){
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "folders";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["key_id"] = "int";
		$this->dbValues["parent_id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbValues["created_at"] = "datetime";
		$this->dbValues["updated_at"] = "datetime";

		$this->relations["properties"]["Key"] = null;
		$this->relations["methods"]["Key"] = "GetKey";
		$this->relations["lazyload"]["Key"] = "true";

		$this->relations["properties"]["Files"] = null;
		$this->relations["methods"]["Files"] = "GetFiles";
		$this->relations["lazyload"]["Files"] = "true";

		$this->relations["properties"]["Parent"] = null;
		$this->relations["methods"]["Parent"] = "GetParent";
		$this->relations["lazyload"]["Parent"] = "true";

		$this->relations["properties"]["Children"] = null;
		$this->relations["methods"]["Children"] = "GetChildren";
		$this->relations["lazyload"]["Children"] = "true";
	}

	public function GetControl() {
		return new \MagratheaExplorer\Folder\Base\FolderControlBase();
	}

	// >>> relations:
	public function GetKey(){
		if($this->relations["properties"]["Key"] != null) return $this->relations["properties"]["Key"];
		$this->relations["properties"]["Key"] = new \MagratheaExplorer\Key\Key($this->key_id);
		return $this->relations["properties"]["Key"];
	}
	public function GetFiles(){
		if($this->relations["properties"]["Files"] != null) return $this->relations["properties"]["Files"];
		$pk = $this->dbPk;
		$this->relations["properties"]["Files"] = \MagratheaExplorer\File\Base\FileControlBase::GetWhere(["folder_id" => $this->$pk]);
		return $this->relations["properties"]["Files"];
	}
	// root folders have parent_id = NULL -- unlike the rest of this generated shape, this
	// getter needs a hand-added null guard so it never tries to load a Folder with id 0/null.
	public function GetParent(){
		if($this->relations["properties"]["Parent"] != null) return $this->relations["properties"]["Parent"];
		if(empty($this->parent_id)) return null;
		$this->relations["properties"]["Parent"] = new \MagratheaExplorer\Folder\Folder($this->parent_id);
		return $this->relations["properties"]["Parent"];
	}
	public function GetChildren(){
		if($this->relations["properties"]["Children"] != null) return $this->relations["properties"]["Children"];
		$pk = $this->dbPk;
		$this->relations["properties"]["Children"] = \MagratheaExplorer\Folder\Base\FolderControlBase::GetWhere(["parent_id" => $this->$pk]);
		return $this->relations["properties"]["Children"];
	}

}
