<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2026-09-08]

namespace MagratheaExplorer\Folder\Base;

use Magrathea2\MagratheaModelControl;

class FolderControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaExplorer\Folder";
	protected static $modelName = "Folder";
	protected static $dbTable = "folders";
}
