<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2026-09-08]

namespace MagratheaExplorer\Key\Base;

use Magrathea2\MagratheaModelControl;

class ScheduledDeletionControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaExplorer\Key";
	protected static $modelName = "ScheduledDeletion";
	protected static $dbTable = "scheduled_deletions";
}
