<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2026-09-08]

namespace MagratheaExplorer\Key\Base;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class ScheduledDeletionBase extends MagratheaModel implements iMagratheaModel {

	public $id, $key_id, $requested_at, $execute_at, $cancelled_at;
	protected $autoload = null;

	public function __construct( $id=0 ){
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "scheduled_deletions";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["key_id"] = "int";
		$this->dbValues["requested_at"] = "datetime";
		$this->dbValues["execute_at"] = "datetime";
		$this->dbValues["cancelled_at"] = "datetime";

		$this->relations["properties"]["Key"] = null;
		$this->relations["methods"]["Key"] = "GetKey";
		$this->relations["lazyload"]["Key"] = "true";
	}

	public function GetControl() {
		return new \MagratheaExplorer\Key\Base\ScheduledDeletionControlBase();
	}

	// >>> relations:
	public function GetKey(){
		if($this->relations["properties"]["Key"] != null) return $this->relations["properties"]["Key"];
		$this->relations["properties"]["Key"] = new \MagratheaExplorer\Key\Key($this->key_id);
		return $this->relations["properties"]["Key"];
	}

}
