<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2026-09-08]

namespace MagratheaExplorer\File\Base;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class FileBase extends MagratheaModel implements iMagratheaModel {

	public $id, $token, $thumbnail_token, $key_id, $folder_id, $name, $storage_path;
	public $extension, $mime_type, $file_type, $size, $width, $height, $duration, $no_convert;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct( $id=0 ){
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "files";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["token"] = "string";
		$this->dbValues["thumbnail_token"] = "string";
		$this->dbValues["key_id"] = "int";
		$this->dbValues["folder_id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbValues["storage_path"] = "string";
		$this->dbValues["extension"] = "string";
		$this->dbValues["mime_type"] = "string";
		$this->dbValues["file_type"] = "string";
		$this->dbValues["size"] = "int";
		$this->dbValues["width"] = "int";
		$this->dbValues["height"] = "int";
		$this->dbValues["duration"] = "int";
		$this->dbValues["no_convert"] = "boolean";
		$this->dbValues["created_at"] = "datetime";
		$this->dbValues["updated_at"] = "datetime";

		$this->relations["properties"]["Key"] = null;
		$this->relations["methods"]["Key"] = "GetKey";
		$this->relations["lazyload"]["Key"] = "true";

		$this->relations["properties"]["Folder"] = null;
		$this->relations["methods"]["Folder"] = "GetFolder";
		$this->relations["lazyload"]["Folder"] = "true";

		$this->relations["properties"]["Tags"] = null;
		$this->relations["methods"]["Tags"] = "GetTags";
		$this->relations["lazyload"]["Tags"] = "true";
	}

	public function GetControl() {
		return new \MagratheaExplorer\File\Base\FileControlBase();
	}

	// >>> relations:
	public function GetKey(){
		if($this->relations["properties"]["Key"] != null) return $this->relations["properties"]["Key"];
		$this->relations["properties"]["Key"] = new \MagratheaExplorer\Key\Key($this->key_id);
		return $this->relations["properties"]["Key"];
	}
	public function GetFolder(){
		if($this->relations["properties"]["Folder"] != null) return $this->relations["properties"]["Folder"];
		$this->relations["properties"]["Folder"] = new \MagratheaExplorer\Folder\Folder($this->folder_id);
		return $this->relations["properties"]["Folder"];
	}
	// many-to-many through the plain `file_tags` join table (composite PK, no Model/Control of its own)
	public function GetTags(){
		if($this->relations["properties"]["Tags"] != null) return $this->relations["properties"]["Tags"];
		$this->relations["properties"]["Tags"] = \MagratheaExplorer\File\FileTagControl::GetTagsForFile($this->id);
		return $this->relations["properties"]["Tags"];
	}

}
