<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2026-09-22]

namespace MagratheaExplorer\Share\Base;

use Magrathea2\MagratheaModelControl;

class ShareControlBase extends MagratheaModelControl {
	protected static $modelNamespace = "MagratheaExplorer\Share";
	protected static $modelName = "Share";
	protected static $dbTable = "shares";
}
