<?php
## FILE GENERATED BY MAGRATHEA.
## This file was automatically generated and changes can be overwritten through the admin
## -- date of creation: [2026-09-22]

namespace MagratheaExplorer\Share\Base;

use Magrathea2\iMagratheaModel;
use Magrathea2\MagratheaModel;

class ShareBase extends MagratheaModel implements iMagratheaModel {

	// hand-edited: added $uuid (see MagratheaStart() below) -- regenerating this file
	// through the admin drops it and breaks inserts against the NOT NULL column.
	public $id, $uuid, $key_id, $file_id, $folder_id, $views, $last_viewed_at;
	public $created_at, $updated_at;
	protected $autoload = null;

	public function __construct( $id=0 ){
		$this->MagratheaStart();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function MagratheaStart(){
		$this->dbTable = "shares";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		// hand-edited: declared "uuid" so Insert() mints it automatically (see
		// MagratheaModel.php's CreateInsertQuery()) -- this one value is both the row's
		// public identity AND the link secret; there is no second token column.
		$this->dbValues["uuid"] = "uuid";
		$this->dbValues["key_id"] = "int";
		$this->dbValues["file_id"] = "int";
		$this->dbValues["folder_id"] = "int";
		$this->dbValues["views"] = "int";
		$this->dbValues["last_viewed_at"] = "datetime";
		$this->dbValues["created_at"] = "datetime";
		$this->dbValues["updated_at"] = "datetime";

		$this->relations["properties"]["Key"] = null;
		$this->relations["methods"]["Key"] = "GetKey";
		$this->relations["lazyload"]["Key"] = "true";

		$this->relations["properties"]["File"] = null;
		$this->relations["methods"]["File"] = "GetFile";
		$this->relations["lazyload"]["File"] = "true";

		$this->relations["properties"]["Folder"] = null;
		$this->relations["methods"]["Folder"] = "GetFolder";
		$this->relations["lazyload"]["Folder"] = "true";
	}

	public function GetControl() {
		return new \MagratheaExplorer\Share\Base\ShareControlBase();
	}

	// >>> relations:
	public function GetKey(){
		if($this->relations["properties"]["Key"] != null) return $this->relations["properties"]["Key"];
		$this->relations["properties"]["Key"] = new \MagratheaExplorer\Key\Key($this->key_id);
		return $this->relations["properties"]["Key"];
	}
	// exactly one of file_id/folder_id is ever set (see the chk_share_target constraint), so
	// both getters need a hand-added null guard -- the generated shape has none and would try
	// to load a File/Folder with id 0/null for whichever side of the share is unused.
	public function GetFile(){
		if($this->relations["properties"]["File"] != null) return $this->relations["properties"]["File"];
		if(empty($this->file_id)) return null;
		$this->relations["properties"]["File"] = new \MagratheaExplorer\File\File($this->file_id);
		return $this->relations["properties"]["File"];
	}
	public function GetFolder(){
		if($this->relations["properties"]["Folder"] != null) return $this->relations["properties"]["Folder"];
		if(empty($this->folder_id)) return null;
		$this->relations["properties"]["Folder"] = new \MagratheaExplorer\Folder\Folder($this->folder_id);
		return $this->relations["properties"]["Folder"];
	}

}
